
<body>
    <h2>Iniciar sesión</h2>
    

    <?php if (isset($error)): ?>
        <p style="color: red;"><?php echo htmlspecialchars($error); ?></p>
    <?php endif; ?>

    <form action="login" method="post"> 
        <label for="name">Usuario:</label> 
        <input type="text" id="name" name="name" required><br><br>

        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required><br><br>

        <input type="submit" value="Iniciar sesión">
    </form>
</body>
</html>
