<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL; ?>">
    <title>Lista de Autos</title>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>Css/style.css"> <!-- Incluye tu CSS -->
</head>
<body>
<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
?>

<header>
    <div class="container">
        <h1>Lista de Autos</h1>
        <nav>
            <ul>
                <li><a href="<?php echo BASE_URL; ?>marcas">Inicio</a></li>
                <li><a href="<?php echo BASE_URL; ?>autos">Ver Todos los Autos</a></li> 
                
                <?php if (isset($_SESSION['ID_USER'])):  ?>
                    <li><a href="<?php echo BASE_URL; ?>logout">Cerrar Sesión</a></li>
                <?php else: ?>
                    <li><a href="<?php echo BASE_URL; ?>login">Logueo</a></li>
                <?php endif; ?>
            </ul>
        </nav>
    </div>
    
</header>

</body>
</html>
